#!/bin/bash


## Run Mr.Bayes to create bayesian based phylo tree
## adapted from usda.../run_tree_3...sh
##
## Run after: run_irr_prokka.sh
## replaces the RAxML max likelyhood tree

## Mr.Bayes didn't work.  complain seq too long (overall .nex file is much larger than usda ee1352, which had 137 taxa, yet file size is much smaller.  probably cuz these samples are much more diverse, thus much more snp diff, more than the Mr.Bayes parser can handle.  so this script not useful.

## probably have to use .tre from RAxML. 


## run as: sbatch run_tree_step3.sh


#SBATCH --job-name=mrBayes_irrExp
###SBATCH --account=scs
#SBATCH --account=fc_graham
#SBATCH --partition=savio4_htc
####SBATCH --partition=savio3
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1             ## mb is single threaded parallel  savio3: 32, savio4: 56   
#SBATCH --time=71:00:00
#SBATCH --mem=401G                  # Memory required per node ## savio4 has 512G

## beagle could use multiple core...

## be careful with the path each of the function cd into  !!   mostly done in main() before calling the fn now.

#DataDir=~/gs/fc_graham/PRISA/Assemblies
#DataDir=/global/scratch/users/tin/fc_graham/stec_usda_Env_EcO157/Fasta4Prokka_EE1394/fasta4tree_cgSTee1352
DataDir=/global/home/users/tin/gs/dataCache/ChristopherLeBoaWGSdata_irrigation_exposure_2026/AI-5395_results/AI-5395_assembly/PROKKA_gff
CurrentDir=$( pwd )
Thread=1 

######################################################################
######################################################################


######################################################################
# need gff to be 8.3 exactly, for paup ++
# see rename script in destination dir ++
######################################################################


######################################################################
# MrBayes
######################################################################

run_mb () {
	#cd /global/home/users/tin/gs/tin-gh/mission2022/prisa/ANIM66_MB
	#cd $DataDir
	#cd PROKKA

	# VVV-- this path for vector still works in EL8 (it is on the vast now)
	/clusterfs/vector/home/groups/software/sl-7.x86_64/modules/phylotool/u20.04/mb -i ECirr_exp.nex << EOF
execute ECirr_exp.nex
EOF
	##module purge  # cuz use intel libs, has working beagle, but for CPU only
	##module load mrbayes
	##/clusterfs/vector/home/groups/software/sl-7.x86_64/modules/mrbayes/3.2.6/bin/mb -i mb_anim66itv.nex
	#~~ Sn50: https://github.com/tin6150/MrBayes/tree/docker-sn50  but not placed in savio?
	#~~ /clusterfs/vector/home/groups/software/sl-7.x86_64/modules/mrbayes/3.2.7a/mb    -i mb_anim66itv.nex
	#~~    BEAGLE library is not linked to this executable.
	#~~ rebuilding w/ CUDA

# oh, Mr.Bayes need .nex as input, and previously the .nex was generated by paup.
# see convert_phy_2_nex.py  append_cmd_to_nex.py  to create nexus file with Mr.Bayes cmd at the end.

#mb> mcmcp ngen=20000 nruns=1 nchains=1 				 # ? ~ chain lenght = 20k nrun=1 took 10min
#mb> mcmcp savebrlens=yes              
#mb> mcmcp printfreq=1000 samplefreq=1000    
#mb> mcmcp diagnfreq=2500 diagnstat=maxstddev            # converge diag settings 
#mb> mcmcp filename=MB_anim66itv_uni                     # filename prefix, _uni for uniform mcmc ??

#mb> mcmcp ngen=300000 nruns=1 nchains=1 				 # ? ~ chain lenght = 300k nrun=1 took 10min
#mb> mcmcp filename=MB_anim66itv_uni300k                 # filename prefix, _uni300k
#mb> mcmcp printfreq=5000 samplefreq=5000    
	
	#cd -
	#cd ..
}

######################################################################
######################################################################

run_tbd () {
	singularity exec /clusterfs/vector/home/groups/software/sl-7.x86_64/modules/phylotool/u20.04/phylotool.sif run_gubbins
	#tbd /clusterfs/vector/home/groups/software/sl-7.x86_64/modules/phylotool/u20.04/run_gubbins
	singularity exec /clusterfs/vector/home/groups/software/sl-7.x86_64/modules/snippy/4.6.0/snippy.sif /usr/local/bin/snippy 
	/clusterfs/vector/home/groups/software/sl-7.x86_64/modules/snippy/4.6.0/snippy
	# /clusterfs/vector/home/groups/software/sl-7.x86_64/modules/beast/2.6.4/beast
	# /clusterfs/vector/home/groups/software/sl-7.x86_64/modules/beast/2.6.4/beast2.6.4-beagle.sif --beagle_Info #??

}

######################################################################


main () {
    hostname; uptime; date
	setup
	cd $DataDir
	#run_prokka
	#cherry_pick_gff
	#run_roary
  	#run_snp-sites 
	#run_paup
	run_mb
	#run_tbd
	cd $CurrentDir
	echo "~~The End~~"
    hostname; uptime; date
}


main	


